### ISSUE TITLE
Meta; retrieve custom field created by Wordpress plugin

### ISSUE THREAD

**Issue by MarcoTroost** [corcel/corcel#200]
Hi Junior Grossi,

Thank you for this great package! It's really saved me a lot of time, not having to join all sort of tables. I have a question though:

I've installed a plugin (All in one SEO package), that creates extra records in de wp_postmeta table. When i try to query these custom records using Corcel (e.g. $artikel->meta->_aioseop_description), i get no results. 

```
                @foreach($artikelen as $artikel)
                    {{ $artikel->title }} <br />
                    {{ $artikel->image }} <br />
                    {{ $artikel->slug }} <br />
                    {{ $artikel->taxonomies()->first()->term->name}} <br />
                    {{ $artikel->taxonomies()->first()->term->slug }} <br />
                    {{ $artikel->meta->_aioseop_description }} <br />

                    <br />
                    <br />
                @endforeach
```

N.B. $artikel->meta->_edit_last does give results.

Do you know how i can fix this?

Kind regards,

Marco Troost

**Comment by jgrossi** [comment]
Hi @MarcoTroost sorry for the late answer. I've been a little busy these last days :-)

About your questions I suggest you to check how `All in one SEO package` stores custom fields in the WP database. Take a look if really exists a row in `wp_postmeta` table where `meta_key = _aioseio_description`. It it really exists Corcel should return it correctly.

Otherwise, if this doesn't work please let me know and send the structure how that plugins is storing data and we can improve Corcel adding new features to it.

Cheers!

**Comment by jgrossi** [comment]
@MarcoTroost did you fix that?
